# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-CD-Production

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  Deployment:
    runs-on: self-hosted
    steps:
      - name: Update main branch
        run: git pull

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Restart application
        run: pm2 restart app-kapipay-prod
