name: CI/CD Develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
      
jobs:
  CI:
   runs-on: ubuntu-latest
   steps:
    - name: Development Deploy
      uses: actions/setup-node@v2
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
     #  //// GARYGROSSGARTEN
     - uses: actions/checkout@v2
     - name: Development Deploy to Digital Ocean
       uses: garygrossgarten/github-action-ssh@release
       with:
         command: cd /home/develop/KapiPay-Front && bash ./deploy.sh         
         host: ${{ secrets.SSH_DEVELOP_HOST_SERVER }}
         username: root
         privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
