name: CI/CD-Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Production Deploy
        uses: actions/setup-node@v2
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      #  //// GARYGROSSGARTEN
      - uses: actions/checkout@v2
      - name: Development Deploy to Digital Ocean
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /home/deploy/KapiPay-Front/deploy && bash ./production.sh
          host: ${{ secrets.SSH_HOST_SERVER }}
          username: ${{ secrets.SSH_USERNAME}}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
